version: '3.3'

services:
  php:
    build:
      context: ./build/php
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
      - ./logs:/logs
      - ./build/php/site.ini:/usr/local/etc/php/conf.d/site.ini
    restart: unless-stopped
 
  db:
    image: mysql:5.7
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: unless-stopped

  mongodb:
    image: mongo:4.2.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    restart: unless-stopped

  nginx:
    build:
      context: ./build/nginx
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
      - ./logs:/logs
      - ./build/nginx/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - 1234:80
    restart: unless-stopped
